# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kPSLBbM8c6Z-hMXHJz63IvdeI6hbaUlu
"""

import numpy as np
import math
import scipy.stats as sp
import matplotlib.pyplot as plt

def binom_dis(n, x, p):return math.comb(n, x) * (p**x) * ((1-p)**(n-x))
def Pois_dis(x, t, k):return np.exp(-t*k)*(np.power(k*t, x)/math.factorial(x))
def Exp_dis(x, t):return t*np.exp(-t * x)
def norm_dis(x, m, s):return ((1/(s*np.sqrt(2*np.pi)))*np.exp(-((x-m)**2)/(2*s**2)))

n, p, t, m, s = 100, 0.4, 4.8, 10, 3

x_values = np.arange(0, n+1)
custom_pmf = [binom_dis(n, x, p) for x in x_values]
scipy_pmf = sp.binom.pmf(x_values, n, p)

plt.figure(figsize=(8, 5))
plt.subplot(1,2,2);plt.bar(x_values, custom_pmf, alpha=0.5, label='Custom PMF', color = "red")
plt.subplot(1,2,1);plt.bar(x_values, scipy_pmf, alpha=0.5, label='Scipy PMF')
plt.title('Comparison of Custom PMF and Scipy PMF for Binomial Distribution')
plt.xlabel('Number of Successes')
plt.ylabel('Probability')
plt.legend()
plt.show()

t_values = np.arange(0, 10)
custom_pmf = [Pois_dis(x, t, 1) for x in t_values]
scipy_pmf = sp.poisson.pmf(t_values, t)

plt.figure(figsize=(8, 5))
plt.subplot(1,2,2);plt.bar(t_values, custom_pmf, alpha=0.5, label='Custom PMF' ,color = "red")
plt.subplot(1,2,1);plt.bar(t_values, scipy_pmf, alpha=0.5, label='Scipy PMF')
plt.title('Comparison of Custom PMF and Scipy PMF for Poisson Distribution')
plt.xlabel('Number of Events')
plt.ylabel('Probability')
plt.legend()
plt.show()

x_values = np.linspace(0, 5, 100)
custom_pdf = [Exp_dis(x, t) for x in x_values]
scipy_pdf = sp.expon.pdf(x_values, scale=1/t)

plt.figure(figsize=(8, 5))
plt.subplot(1,2,2);plt.plot(x_values, custom_pdf, label='Custom PDF', color='blue')
plt.subplot(1,2,1);plt.plot(x_values, scipy_pdf, label='Scipy PDF', color='orange')
plt.title('Comparison of Custom PDF and Scipy PDF for Exponential Distribution')
plt.xlabel('Random Variable (x)')
plt.ylabel('Probability Density')
plt.legend()
plt.show()

x_values = np.linspace(0, 20, 100)
custom_pdf = [norm_dis(x, m, s) for x in x_values]
scipy_pdf = sp.norm.pdf(x_values, loc=m, scale= s)

plt.figure(figsize=(8, 5))
plt.subplot(1,2,2);plt.plot(x_values, custom_pdf, label='Custom PDF', color='blue')
plt.subplot(1,2,1);plt.plot(x_values, scipy_pdf, label='Scipy PDF', color='orange')
plt.title('Comparison of Custom PDF and Scipy PDF for Normal Distribution')
plt.xlabel('Random Variable (x)')
plt.ylabel('Probability Density')
plt.legend()
plt.show()